### ISSUE TITLE
Execution order of multiple bees

### ISSUE THREAD

**Issue by m-ender** [m-lohmann/BeeswaxEsolang.jl#2]
Unless I'm overlooking it, the language spec does not describe how multiple bees are processed. Are there any guarantees on how they are processed, or could on bee be run until it is deleted and then the next one is run? Are they processed "simultaneously" in that each bee does one step/command, and then they all do the next step and so on? If so, are there any guarantees about the order they are processed in?

**Comment by m-lohmann** [comment]
I should add a section describing how the bees are created and handled by the interpreter. I think I did that on Codegolf Stackexchange but totally missed it on Github.

Yes, the processing order of the bees is is guaranteed.

It’s actually quite easy.

The code is read column-wise, each column is read top to bottom (top left being column 1,row 1), to find starting points for the bees.

The relevant snippet from `beeswax.jl` (lines184 to 193):

``` julia
    # generate IPs
    deb.d>2 ? println("generating bees..."):nothing
    @inbounds for c=1:cols
        @inbounds for r=1:rows
            arena.a[r,c] == ('*') ? pointer_all(list,r,c):
            arena.a[r,c] == ('\\')? pointer_diag1(list,r,c):
            arena.a[r,c] == ('/') ? pointer_diag2(list,r,c):
            arena.a[r,c] == ('_') ? pointer_horiz(list,r,c):nothing
        end
    end
```

If a starting point is found, order of creation always follows this pattern:

```
  2 1
 3 β 0
  4 5
```

All bees are stored in a stack, and newly created bees are pushed on top of this stack in the order of creation.
So, for `*`, the bees pushed on top of the stack are in this order:
`[..., 0, 1, 2, 3, 4, 5]•`, `•` marking the top of the stack
For `\`: `[..., 2, 5]•`
For `/`: `[..., 1, 4]•`
For `_`: `[..., 0, 3]•`

The spreading/cloning instructions `X, E, H, W` work in the same way. You can check `bwinstructions.jl` for the exact order of pushing bees on the stack for each of these commands. The code should be self-explanatory (I hope) ;)

The relevant code snippets for these instructions are

For instruction `X`, with more comments than necessary ;)

``` julia
#   X (dir 012345 spread)
    for d=0:5     #go through direction 0 to 5
        if d==list[ind].dir  #if direction is the same as the original direction of the bee
            move(list,ind)   #just change the bee’s coordinates according to the bee’s direction
        elseif d==(list[ind].dir+3)%6  #if the direction is opposite of the bee’s original direction
            nothing                            #don’t create a bee, just do nothing
        else
            push!(list,Pointer(deepcopy(list[ind].lstack),[r,c],d,0,false,true))   # push a clone of the original bee on the pointer stack, but with direction d
        end
    end
```

For instruction `E`

``` julia
#   E (dir 03 spread)
function pointer_spread03(list::Array{Pointer,1},ind::Int,r::Int,c::Int)
    if list[ind].dir==0 || list[ind].dir==3
        nothing
    else
        list[ind].dir=0
        push!(list,Pointer(deepcopy(list[ind].lstack),[r,c],3,0,false,true))
    end
end
```

For instruction `H`

``` julia
#   H (dir 14 spread)
function pointer_spread14(list::Array{Pointer,1},ind::Int,r::Int,c::Int)
    if list[ind].dir==1 || list[ind].dir==4
        nothing
    else
        list[ind].dir=1
        push!(list,Pointer(deepcopy(list[ind].lstack),[r,c],4,0,false,true))
    end
end
```

For instruction `W`

``` julia
#   W (dir 25 spread)
function pointer_spread25(list::Array{Pointer,1},ind::Int,r::Int,c::Int)
    if list[ind].dir==2 || list[ind].dir==5
        nothing
    else
        list[ind].dir=2
        push!(list,Pointer(deepcopy(list[ind].lstack),[r,c],5,0,false,true))
    end
end
```

During program execution, for each tick, the instruction for the last bee pushed on the stack is executed first, then the following down to the botton of the stack. If bees leave the honeycomb, they get marked as dead, and after executing all instructions, the stack gets cleaned up. Dead bees get removed, but the general order of bees stays the same.

My “Hello World!” codegolf example demonstrates the execution order of bees quite nicely.
It prints `Hello, World!` to the console.

```
r  l
 l o
  ``
ol`*`,d!
   ``
   e H
   W
```

The prettyprint version is a bit easier on the eyes ;)

```
      r     l
       l   o
        ` `
   o l ` * ` , d !
        ` `
       e   H
      W
```

I hope my explanation is helpful.

**Comment by m-ender** [comment]
Yes, that's very clear and helpful, thanks. Feel free to close this once you've added it to the readme. (You might also want to update esolangs then.)

**Comment by m-lohmann** [comment]
Please have a look if the `Readme.md` addition is good enough or if I should change something.
I have also updated the Esolangs article accordingly.

**Comment by m-lohmann** [comment]
`Readme.md` and Esolangs article updated.
